### ISSUE TITLE
Suggestion load bug

### ISSUE THREAD

**Issue by st49617** [st49617/Voting-system#25]
1) Suggestion Entita nemá defaultní konstruktor

2) Při vytváření SuggestionDto To padá na načítání meetingu¨

Jinak super práce.
S tím @RequestBody parametrem je to dobře a budeme to používat. Já sem si jenom neuměl představit jak to bude fungovat

**Comment by Burdis28** [comment]
Jak to padá na načítání meetingu? Jaká chyba? Co to vyhodilo za výjimku?

**Comment by st49617** [comment]
Netuším už. Jenom vím že když sem to zakomentoval tak to fungovalo.

**Comment by Burdis28** [comment]
To bude nejspíš tím, že v databázi žádný Meeting není a JPA místo aby vracelo null hodnotu, tak vyhodí exception NoSuchElement nebo něco takovýho. Opravím try catchem a zaloguju.

**Comment by st46619** [comment]
Zkousim to ted na jednom meetingu s jednou suggestion:
No default constructor for entity: : cz.upce.votingsystemapplication.model.Suggestion; nested exception is org.hibernate.InstantiationException: No default constructor for entity: : cz.upce.votingsystemapplication.model.Suggestion
(...)
Caused by: org.hibernate.InstantiationException: No default constructor for entity: : cz.upce.votingsystemapplication.model.Suggestion

Asi to ten konstruktor chce. :D
